version: '3.4'

services:
  database:
    image: postgres:16-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_database
    environment:
      POSTGRES_DB: ${DB_DATABASE:-app}
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASS:-!ChangeMe!}
      PGDATA: /var/lib/postgresql/data
      # Default path is
      # PGDATA: /var/lib/postgresql/data
    volumes:
      - ../../var/db/data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./db/data:/var/lib/postgresql/data:rw
    ports:
      - "${COMPOSE_IP}:${COMPOSE_PORT_DB}:${DB_PORT}"
    restart: unless-stopped

  php:
    build:
      dockerfile: ./Dockerfile
      target: php_dev
    container_name: ${COMPOSE_PROJECT_NAME}_php
    depends_on:
      - database
#    environment:
#      DATABASE_URL: postgresql://${DB_USER:-user}:${DB_PASS:-!ChangeMe!}@database:5432/${DB_DATABASE:-app}?serverVersion=${POSTGRES_VERSION:-16}&charset=${POSTGRES_CHARSET:-utf8}
    volumes:
      - ../../:/var/www/
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/docker-healthcheck.sh:/usr/local/bin/docker-healthcheck
      - ./php/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint

  nginx:
    image: nginx:1-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    depends_on:
      - php
    ports:
      - "${COMPOSE_IP}:${COMPOSE_PORT_HTTP}:80"
      - "${COMPOSE_IP}:8143:443"
    volumes:
      - ../../:/var/www/
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
